#!/bin/sh
set -o verbose
OUT=../../output
INCLUDES="-I. -I.. -I../apu/"
CCFLAGS="-U__linux -DLSB_FIRST -DHTML -DUSE_SDL -DSOUND -fomit-frame-pointer -fno-exceptions -fno-rtti -pedantic -Wall -W -Wno-unused-parameter -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_MKSTEMP -DHAVE_STRINGS_H -DHAVE_SYS_IOCTL_H -DHAVE_STDINT_H -DRIGHTSHIFT_IS_SAR -Wno-c++11-extensions"
PPU_OPT=""

cleanOutput() {
  rm -f $OUT/*
}

clean() {
  find ../. -type f -name '*.o' -delete
  find ../. -type f -name 'a.out.*' -delete
}

compile() {
    echo $CCFLAGS
    echo $PPU_OPT
    emcc $INCLUDES $CCFLAGS -O3 ../snapshot.cpp -c -o ../snapshot.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/apu.cpp -c -o ../apu/apu.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/SNES_SPC.cpp -c -o ../apu/SNES_SPC.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/SNES_SPC_misc.cpp -c -o ../apu/SNES_SPC_misc.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/SNES_SPC_state.cpp -c -o ../apu/SNES_SPC_state.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/SPC_DSP.cpp -c -o ../apu/SPC_DSP.o
    emcc $INCLUDES $CCFLAGS -O3 ../apu/SPC_Filter.cpp -c -o ../apu/SPC_Filter.o
    emcc $INCLUDES $CCFLAGS -O3 ../bsx.cpp -c -o ../bsx.o
    emcc $INCLUDES $CCFLAGS -O3 ../c4.cpp -c -o ../c4.o
    emcc $INCLUDES $CCFLAGS -O3 ../c4emu.cpp -c -o ../c4emu.o
    emcc $INCLUDES $CCFLAGS -O3 ../clip.cpp -c -o ../clip.o
    emcc $INCLUDES $CCFLAGS -O3 ../controls.cpp -c  -o ../controls.o
    emcc $INCLUDES $CCFLAGS -O3 ../cpu.cpp -c  -o ../cpu.o
    emcc $INCLUDES $CCFLAGS -O3 ../cpuexec.cpp -c  -o  ../cpuexec.o
    emcc $INCLUDES $CCFLAGS -O3 ../cpuops.cpp -c  -o ../cpuops.o
    emcc $INCLUDES $CCFLAGS -O3 ../dma.cpp -c  -o ../dma.o
    emcc $INCLUDES $CCFLAGS -O3 ../dsp.cpp -c  -o ../dsp.o
    emcc $INCLUDES $CCFLAGS -O3 ../dsp1.cpp -c  -o ../dsp1.o
    emcc $INCLUDES $CCFLAGS -O3 ../dsp2.cpp -c  -o ../dsp2.o
    emcc $INCLUDES $CCFLAGS -O3 ../dsp3.cpp -c  -o ../dsp3.o
    emcc $INCLUDES $CCFLAGS -O3 ../dsp4.cpp -c  -o ../dsp4.o
    emcc $INCLUDES $CCFLAGS -O3 ../fxinst.cpp -c  -o ../fxinst.o
    emcc $INCLUDES $CCFLAGS -O3 ../fxemu.cpp -c  -o ../fxemu.o
    emcc $INCLUDES $CCFLAGS -O3 ../gfx.cpp -c  -o ../gfx.o
    emcc $INCLUDES $CCFLAGS -O3 ../globals.cpp -c   -o ../globals.o
    emcc $INCLUDES $CCFLAGS -O3 ../memmap.cpp -c   -o ../memmap.o
    emcc $INCLUDES $CCFLAGS -O3 ../obc1.cpp -c  -o ../obc1.o
    emcc $INCLUDES $CCFLAGS $PPU_OPT ../ppu.cpp -c  -o ../ppu.o
    emcc $INCLUDES $CCFLAGS -O3 ../reader.cpp -c  -o ../reader.o
    emcc $INCLUDES $CCFLAGS -O3 ../sa1.cpp -c  -o ../sa1.o
    emcc $INCLUDES $CCFLAGS -O3 ../sa1cpu.cpp -c   -o ../sa1cpu.o
    emcc $INCLUDES $CCFLAGS -O3 ../sdd1.cpp -c  -o ../sdd1.o
    emcc $INCLUDES $CCFLAGS -O3 ../sdd1emu.cpp -c  -o ../sdd1emu.o
    emcc $INCLUDES $CCFLAGS -O3 ../seta.cpp -c  -o ../seta.o
    emcc $INCLUDES $CCFLAGS -O3 ../seta010.cpp -c  -o ../seta010.o
    emcc $INCLUDES $CCFLAGS -O3 ../seta011.cpp -c  -o ../seta011.o
    emcc $INCLUDES $CCFLAGS -O3 ../seta018.cpp -c   -o ../seta018.o
    emcc $INCLUDES $CCFLAGS -O3 ../snes9x.cpp -c  -o ../snes9x.o
    emcc $INCLUDES $CCFLAGS -O3 ../spc7110.cpp -c  -o ../spc7110.o
    emcc $INCLUDES $CCFLAGS -O3 ../srtc.cpp -c  -o ../srtc.o
    emcc $INCLUDES $CCFLAGS -O3 ../tile.cpp -c  -o ../tile.o
    emcc $INCLUDES $CCFLAGS -O3 sdlmain.cpp -c  -o sdlmain.o
    emcc $INCLUDES $CCFLAGS -O3 sdlinput.cpp -c  -o sdlinput.o
    emcc $INCLUDES $CCFLAGS -O3 sdlvideo.cpp -c  -o sdlvideo.o
    emcc $INCLUDES $CCFLAGS -O3 sdlaudio.cpp -c  -o sdlaudio.o
}

link () {
    emcc \
    -O3 \
    ../apu/apu.o ../apu/SNES_SPC.o ../apu/SNES_SPC_misc.o ../apu/SNES_SPC_state.o ../apu/SPC_DSP.o ../apu/SPC_Filter.o ../bsx.o ../c4.o ../c4emu.o  ../clip.o  ../controls.o ../cpu.o ../cpuexec.o ../cpuops.o ../dma.o ../dsp.o ../dsp1.o ../dsp2.o ../dsp3.o ../dsp4.o ../fxinst.o ../fxemu.o ../gfx.o ../globals.o  ../memmap.o  ../obc1.o ../ppu.o ../reader.o ../sa1.o ../sa1cpu.o  ../sdd1.o ../sdd1emu.o ../seta.o ../seta010.o ../seta011.o ../seta018.o  ../snes9x.o ../spc7110.o ../srtc.o ../tile.o sdlmain.o sdlinput.o sdlvideo.o sdlaudio.o ../snapshot.o \
    -lm \
    -lSDL \
    -s EXPORTED_FUNCTIONS="['_main', '_freeze', '_unfreeze', '_set_frameskip', '_set_transparency',  '_run', '_mainloop', '_toggle_display_framerate', '_S9xAutoSaveSRAM', '_get_left_audio_buffer', '_get_right_audio_buffer', '_collect_audio' ]" \
    -s EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap"] \
    -s FORCE_FILESYSTEM=1 \
    -s INITIAL_MEMORY=67108864 \
    -o $OUT/$1.js
}

cleanOutput

clean
compile
link snes9x-chrome-intel

PPU_OPT="-O3"
clean
compile
link snes9x

clean
